name: 02 - Workflow events
on: push
jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "Ive been triggered by an ${{github.event}} event."